/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    BaseFooter: typeof import('./src/components/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    BaseLabel: typeof import('./src/components/BaseLabel.vue')['default']
    BaseLazyImage: typeof import('./src/components/BaseLazyImage.vue')['default']
    BaseRecipe: typeof import('./src/components/BaseRecipe.vue')['default']
    BaseSearchInput: typeof import('./src/components/BaseSearchInput.vue')['default']
    BaseSignInModal: typeof import('./src/components/BaseSignInModal.vue')['default']
    BaseTabs: typeof import('./src/components/BaseTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgView: typeof import('./src/components/SvgView.vue')['default']
  }
}
